name: Update NIH Reporter Data

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight every day
  workflow_dispatch:      # Allow manual triggers

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests plotly numpy kaleido
    
    - name: Run update script
      run: |
        python cumulative_grants_by_award_date.py
    
    - name: Commit and push if changes exist
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add cache/*.json
        git add nih_awards.html
        git add nih_awards.png
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update NIH Reporter data $(date +'%Y-%m-%d')" && git push)